# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

steps:
- script: echo MyMavenAzure pipeline
  displayName: 'Run a one-line script'

- script: mvn clean install
  displayName: 'build maven'
- script: java -jar target/MyMavenApp01-1.0-SNAPSHOT.jar
  displayName: 'Running jar'
